

server:
  port: 80
  tomcat:
    max-threads: 200
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&&allowPublicKeyRetrieval=true&&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
